### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by toonsevrin** [Stremio/stremio-shell#118]
It would be nice to have Snaps as a deployment target.

I tried creating this myself but terribly failed: 
snapcraft.yaml:
```yaml
name: stremio
version: 0.0.1
summary: streaming client
base: core18
description: streaming client
confinement: strict
grade: stable

layout:
  /opt/stremio/node:
    bind: $SNAP_DATA/opt/stremio/node
apps:
    stremio:
        #This will start the server in a tmux session and run stremio on the foreground. For testing we just run stremio itself
        #command: tmux new -d 'node server.js'; stremio
        command: stremio
        desktop: smartcode-stremio.desktop
        plugs:
        - network-bind
        - desktop
        - desktop-legacy
        - wayland
        - unity7
        - x11
        - gsettings
        - opengl
        environment:
          QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms 

parts:
    stremio:
      plugin: qmake
      #override-pull: |
      #  rm -rf opt/stremio/node
      override-build: |
        wget https://dl.strem.io/four/v4.4.10/server.js -o ../install/server.js
        wget https://dl.strem.io/four/v4.4.10/stremio.asar -o ../install/stremio.asar
        qmake && make
        mv ./* ../install/
      stage-packages:
      - tmux
      - nodejs
      - qt5-default
      - libqt5webview5-dev
      - libkf5webengineviewer-dev
      - qml-module-qtwebchannel
      - qml-module-qt-labs-platform
      - qml-module-qtwebengine
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-controls
      - libmpv-dev
      - libslang2
      - libqt5x11extras5
      - xcb
      build-packages:
      - wget
      - build-essential
      - qtcreator
      - qt5-qmake
      - qt5-default
      - pkgconf
      - libssl-dev
      - libqt5webview5-dev
      - libkf5webengineviewer-dev
      - libmpv-dev
      source-type: git
      source: https://github.com/Stremio/stremio-shell.git
```

error message:
```
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.stremio', please create it with 0700 permissions.
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
Qt: Session management error: None of the authentication protocols specified are supported
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QQmlApplicationEngine failed to load component
qrc:/main.qml:2 module "QtWebEngine" is not installed
qrc:/main.qml:4 module "QtQuick.Window" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:12 module "Qt.labs.platform" is not installed
qrc:/main.qml:3 module "QtWebChannel" is not installed
qrc:/main.qml:5 module "QtQuick.Controls" is not installed
qrc:/main.qml:2 module "QtWebEngine" is not installed
qrc:/main.qml:4 module "QtQuick.Window" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:12 module "Qt.labs.platform" is not installed
qrc:/main.qml:3 module "QtWebChannel" is not installed
qrc:/main.qml:5 module "QtQuick.Controls" is not installed
qrc:/main.qml:2 module "QtWebEngine" is not installed
qrc:/main.qml:4 module "QtQuick.Window" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:12 module "Qt.labs.platform" is not installed
qrc:/main.qml:3 module "QtWebChannel" is not installed
qrc:/main.qml:5 module "QtQuick.Controls" is not installed
qrc:/main.qml:2 module "QtWebEngine" is not installed
qrc:/main.qml:4 module "QtQuick.Window" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:12 module "Qt.labs.platform" is not installed
qrc:/main.qml:3 module "QtWebChannel" is not installed
qrc:/main.qml:5 module "QtQuick.Controls" is not installed
qrc:/main.qml:2 module "QtWebEngine" is not installed
qrc:/main.qml:4 module "QtQuick.Window" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:12 module "Qt.labs.platform" is not installed
qrc:/main.qml:3 module "QtWebChannel" is not installed
qrc:/main.qml:5 module "QtQuick.Controls" is not installed
qrc:/main.qml:2 module "QtWebEngine" is not installed
qrc:/main.qml:4 module "QtQuick.Window" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:12 module "Qt.labs.platform" is not installed
qrc:/main.qml:3 module "QtWebChannel" is not installed
qrc:/main.qml:5 module "QtQuick.Controls" is not installed
qrc:/main.qml:2 module "QtWebEngine" is not installed
qrc:/main.qml:4 module "QtQuick.Window" is not installed
qrc:/main.qml:1 module "QtQuick" is not installed
qrc:/main.qml:6 module "QtQuick.Dialogs" is not installed
qrc:/main.qml:12 module "Qt.labs.platform" is not installed
qrc:/main.qml:3 module "QtWebChannel" is not installed
qrc:/main.qml:5 module "QtQuick.Controls" is not installed

QObject::connect: Cannot connect MainApp::receivedMessage(QVariant, QVariant) to (null)::onAppMessageReceived(QVariant, QVariant)

```
